### ISSUE TITLE
Be able to set where in the level the player character starts

### ISSUE THREAD

**Issue by addtheletters** [rmmartin02/Group4Game#48]
Maybe we allow the 'enemies' file to be an 'entities' file and also store the starting character position.

**Comment by ruoyinghao** [comment]
be92dc3d43a2d2be79c343ca997223d70dad16db
* modified entity data file, level -1 indicate character, character get a start position
* modified Logic::LoadEntities to set Character position
* the character doesn't face the "right" direction but I think its alright
